apiVersion: v1
kind: Service
metadata:
  name: web-headless
  labels:
    app: app1
spec:
  ports:
  - port: 8080
    name: web
  clusterIP: None
  selector:
    app: app1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "web-headless"
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: java-session
        image: mahendrshinde/http-session-java:4
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          failureThreshold: 4
          periodSeconds: 10
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: www
          mountPath: /usr/local/tomcat/temp
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  selector:
      app: app1
  ports:
  - port: 80
    targetPort: 8080
